version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  postgresql:
    image: artify-api-postgres
    ports:
      - "5432:5432"
