name: Build

on:
  push:
    paths:
      - 'image-processor/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - '.github/workflows/b.yml'
      - 'docker/kubernetes/image-processor/*.yaml'
    branches-ignore:
      - master
  pull_request:
    paths:
      - 'image-processor/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - '.github/workflows/b.yml'
      - 'docker/kubernetes/image-processor/*.yaml'
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - master

jobs:
  build:
    name: Build for JDK ${{ vars.JAVA_VERSION }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Build
        run: ./gradlew image-processor:clean image-processor:build

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: ./gradlew image-processor:test
