name: Build, publish & deploy

on:
  push:
    paths:
      - 'api/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - '.github/workflows/bpd.yml'
      - 'docker/kubernetes/api/*.yaml'
    branches:
      - master
  pull_request:
    paths:
      - 'api/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - '.github/workflows/bpd.yml'
      - 'docker/kubernetes/api/*.yaml'
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  build:
    name: Build for JDK ${{ vars.JAVA_VERSION }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew clean build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run tests
        run: ./gradlew test

  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: test

    steps:
      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: ./gradlew api:jib -Djib.to.image=winteryfox/artify-api -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_ACCESS_TOKEN }}

  deploy:
    name: Deploy to Kubernetes cluster
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: artify
          cluster-name: artify

      - name: Deploy application
        uses: azure/k8s-deploy@v4
        with:
          manifests: ./docker/kubernetes/api
          action: deploy
          strategy: basic
          pull-images: false
