name: Image Processor

on:
  push:
    paths:
      - 'image-processor/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - '.github/workflows/image-processor.yml'
      - 'docker/kubernetes/image-processor/*.yaml'
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - 'image-processor/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - '.github/workflows/image-processor.yml'
      - 'docker/kubernetes/image-processor/*.yaml'
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build for JDK ${{ vars.JAVA_VERSION }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Build
        run: ./gradlew image-processor:clean image-processor:build

      - name: Run tests
        run: ./gradlew image-processor:test

  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish to Docker Hub
        run: ./gradlew image-processor:jib -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_ACCESS_TOKEN}}
