name: Static Code Analysis

on:
  push:
    paths:
      - 'core/**'
      - 'api/**'
      - 'image-processor/**'
      - '.github/workflows/sca.yml'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Analyse projects
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 19 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info
